# Generated by Django 5.2 on 2026-03-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='meensaje',
            new_name='mensaje',
        ),
    ]
