# Generated by Django 5.2 on 2026-04-09 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_meensaje_notificacion_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='usuario_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_generadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
